# Extra Credit

There are two opportunities for the extra credit that are offered during the course. For each one that you complete, I will add a percentage point to your final grade. Because these opportunities exist, I do not round grades. Extra credit assignments are due when you turn in your project.

## Interview

Interview someone involved in marketing research (Account Executive, Data Analyst, Research Assistant/Associate, etc.) to understand more about their job and write a 1-page summary of the interview (bullet points are fine). Interviews should only last 10-15 minutes so you don't take up too much of the person's time (***worth 1 point on your final average***). Interview questions suggestions:

| a. Asking the individual to walk you through a day from morning until afternoon
| b. Asking them what the best and worst things about their job are
| c. How they got into the field
| d. The most important skills/personality characteristics required for the job
| e. How someone interested in this career might best go about breaking into the field
| f. Any other questions you think are interesting

## Popular Press Articles

Find a current example in the popular press (or video, movie, etc) of a topic we are talking about in class. You will need to detail the example and clearly illustrate how it relates to marketing research and a specific topic discussed in class in a 1-page write-up (provide links to videos, products, or ads if needed). ***Topics need to be approved by me first as no duplicates will be allowed (worth 1 point on your final average).***
