# Scientific writing

TODO: add example/content from Zinser

One of my goals for this course is to help you develop your research writing. Specifically, I would like you to gain some experience writing with an objective and impartial tone. Tone refers to the author’s attitude toward the topic they are writing about, which can be evident by the author’s word choice. Take a look at the two passages below.

- The objective tone is impartial. It doesn’t show positive or negative feelings toward the topic being written. Additionally, it avoids the use of 1st and 2nd person pronouns.
- The subjective tone is personal, emotional, and typically informal.  

The following examples will hopefully help differentiate the two.

1. This place may be shabby, but since my children were born while we lived here, it has a special place in my heart.
   - The tone is sentimental. “It has a special place in my heart,” expresses tender emotions.
2. This isn’t the best apartment in the world, but it’s not that bad.
   - The tone is tolerant. The words “not that bad” suggest that the writer accepts the situation while recognizing it could be better.
3. If only decent jobs were out there, I wouldn’t be reduced to living in this miserable dump.
   - The tone is bitter. The writer presents a situation that forces them to live in a “miserable dump.”
4. This place does need some repairs, but I’m sure the landlord will be making improvements sometime soon.
   - The tone is optimistic. The writer is expecting the apartment to be improved soon.
5. When we move away, we’re planning to release three hundred cockroaches and two mice, so we can leave the place exactly as we found it.
   - The tone is humorous. The writer claims to be planning comic revenge on the landlord by returning the apartment to the terrible condition when the tenants moved in.
6. This is the apartment we live in. It provides shelter.
   - The tone is objective. The writer does not express feelings about the apartment and only states factual information.
